/** 错误码与后端 constants/errorCodes 保持一致，前端按钮/提示据此分支。 */
export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",

  STEP_NOT_FOUND: "STEP_NOT_FOUND",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  BATCH_NOT_FOUND: "BATCH_NOT_FOUND",
  REQUISITION_NOT_FOUND: "REQUISITION_NOT_FOUND",

  PLAN_NOT_APPROVED: "PLAN_NOT_APPROVED",
  PLAN_ALREADY_ARCHIVED: "PLAN_ALREADY_ARCHIVED",
  PLAN_AWAITING_RECHECK: "PLAN_AWAITING_RECHECK",
  PLAN_NOT_SUBMITTED: "PLAN_NOT_SUBMITTED",
  PLAN_RECALC_MISMATCH: "PLAN_RECALC_MISMATCH",

  STEP_ALREADY_FINISHED: "STEP_ALREADY_FINISHED",
  STEP_LOCKED_BY_ARCHIVE: "STEP_LOCKED_BY_ARCHIVE",
  STEP_LOCKED_BY_PEER: "STEP_LOCKED_BY_PEER",
  STEP_EXECUTION_CONFLICT: "STEP_EXECUTION_CONFLICT",
  STEP_IMAGE_MISMATCH: "STEP_IMAGE_MISMATCH",
  STEP_IMAGE_VERSION_REQUIRED: "STEP_IMAGE_VERSION_REQUIRED",

  BATCH_INVALID: "BATCH_INVALID",
  BATCH_INSUFFICIENT: "BATCH_INSUFFICIENT",
  BATCH_QUANTITY_INVALID: "BATCH_QUANTITY_INVALID",
  BATCH_ALREADY_ACTIVE: "BATCH_ALREADY_ACTIVE",

  ARCHIVE_FROZEN: "ARCHIVE_FROZEN",
  IDEMPOTENCY_REPLAY: "IDEMPOTENCY_REPLAY",

  OFFLINE_DRAFT_SAVED: "OFFLINE_DRAFT_SAVED"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
