export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  // 领用链相关
  BATCH_NOT_FOUND: "BATCH_NOT_FOUND",
  BATCH_INACTIVE: "BATCH_INACTIVE",
  BATCH_EXPIRED: "BATCH_EXPIRED",
  BATCH_INSUFFICIENT: "BATCH_INSUFFICIENT",
  STEP_NOT_FOUND: "STEP_NOT_FOUND",
  STEP_COMPLETED: "STEP_COMPLETED",
  PLAN_ARCHIVED: "PLAN_ARCHIVED",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  REQUISITION_CONFLICT: "REQUISITION_CONFLICT",
  REQUISITION_NOT_FOUND: "REQUISITION_NOT_FOUND",
  PLAN_NOT_RECALCULATED: "PLAN_NOT_RECALCULATED",
  LEDGER_INCONSISTENT: "LEDGER_INCONSISTENT",
  IMAGE_EVIDENCE_MISSING: "IMAGE_EVIDENCE_MISSING"
} as const;
